import { Geist, Geist_Mono, Oswald } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// export const metadata = {
//   title: "Motiparadise | fabthefamily",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "Best Villa in Udaipur | Motiparadise",
  description:
    "Escape to a luxurious villa in Udaipur featuring serene views, elegant rooms, bonfire nights, a pure veg restaurant, and modern amenities for perfect gateways.",
  keywords: [
    "best villa in udaipur",
    "villa with private pool in udaipur",
    "private pool villa in udaipur",
    "udaipur resorts with private pool",
    "private villa in udaipur",
    "homestay in udaipur",
    "luxury villa in udaipur",
    "pool villa in udaipur",
    "villa stay in udaipur",
    "room with private pool in udaipur",
    "udaipur villas",
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} antialiased bg-white text-gray-900`}
      >
        {children}
      </body>
    </html>
  );
}
